### ISSUE TITLE
--update argument not allowed

### ISSUE THREAD

**Issue by heikobornholdt** [rubysec/bundler-audit#101]
The `bundle-audit check --update` call mentioned in README does not work for me:
`````
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ gem list | grep bundler-audit
bundler-audit (0.4.0)
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ bundle-audit check --update
ERROR: "bundle-audit check" was called with arguments ["--update"]
Usage: "bundle-audit check"
`````

**Comment by postmodern** [comment]
I just merged that into master, instead of the 0.5.0 branch; ideally feature PRs should be made from the next version branch. The github README will not always represent the current stable version. For documentation of the latest gem, please see the [Documentation](http://www.rubydoc.info/gems/bundler-audit) link.
