### ISSUE TITLE
Travis don't run tests

### ISSUE THREAD

**Issue by dzhlobo** [rubysec/bundler-audit#21]
What is with travis? Why it doesn't run tests?

**Comment by shanecav84** [comment]
@postmodern I'm having an issue in Travis that might be related. I'm testing against multiple versions of a dependency using [these instructions](https://docs.travis-ci.com/user/languages/ruby/#Testing-against-multiple-versions-of-dependencies). The tests fail because `bundler-audit` is unable to find the lockfile. There are two reasons for the issue:

1. `bundler-audit` is looking for `Gemfile.lock` in the current working directory rather than in the directory with the gemfile
2. `bundler-audit` is looking for `Gemfile.lock` rather than tacking `.lock` onto the gemfile name; e.g., a gemfile named `rails_5_0.gemfile` results in the lockfile `rails_5_0.gemfile.lock`

I'd like to propose altering the `Scanner`'s initializer to fallback to the environment variable `BUNDLE_GEMFILE` when a `Gemfile.lock` doesn't exist in the current working directory.
